version: '3.9'

services:
  database:
    container_name: database-service
    environment:
      POSTGRES_PASSWORD: ${DJANGO_DB_PASSWORD}
      POSTGRES_USER: ${DJANGO_DB_USER}
      POSTGRES_DB: ${DJANGO_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DJANGO_DB_USER} -d ${DJANGO_DB_NAME}"]
      interval: 10s
      retries: 5
    image: postgres:latest
    networks:
      default: null
    ports:
      - 5433:5433
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: -p 5433
    restart: unless-stopped

  web:
      build: .
      command: gunicorn your_project_name.wsgi:application --bind 0.0.0.0:3000
      volumes:
        - .:/code
      ports:
        - "3000:3000"
      depends_on:
        - database
      env_file:
        - .env

volumes:
  pgdata: